project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant"))
]




urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from .views import ListRestaurants, DetailRestaurants, dish_details

app_name = 'restaurant.apps.RestaurantConfig'

urlpatterns = [
    path('restaurnts/', ListRestaurants.as_view(), name='list_restaurant'),
    path('restaurnts/<slug:slug>/', DetailRestaurants.as_view(), name='detail_restaurant'),
    path('restaurnt/<slug:restaurant_slug>/<slug:slug>/', dish_details, name='dish_details'),

]

restaurant/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

restaurant_status = (
    ("Open", "Open"),
    ("Closed", "Closed")
)

class Restaurant(models.Model):
    restaurant_id = models.AutoField(_("Restaurant ID"), primary_key=True)
    name = models.CharField(_("Name"), max_length=100)
    description = models.TextField(_("Description"), max_length=350)
    status = models.CharField(_("Status"), max_length=6, choices=restaurant_status, default="Open")
    slug = models.SlugField(_("Slug"), blank=True)
    categories = models.ManyToManyField('Category', verbose_name=_("Category"), related_name='restaurant_categories')
    image = models.ImageField(_("Restaurant Image"), upload_to="Restaurants")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Restaurant, self).save(*args, **kwargs)


class Category(models.Model):
    category_id = models.AutoField(_("Category ID"), primary_key=True)
    name = models.CharField(_("Name"), max_length=150)
    slug = models.SlugField(_("Slug"), blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Dish(models.Model):
    dish_id = models.BigAutoField(_("Dish ID"), primary_key=True)
    name = models.CharField(_("Name"), max_length=150)
    description = models.TextField(_("Description"), max_length=750)
    price =models.DecimalField(_("Price"), max_digits=10, decimal_places=2)
    image = models.ImageField(_("Dish Image"), upload_to="Dish")
    created_at = models.DateTimeField(_("Created at"), default=timezone.now)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    restaurant = models.ForeignKey(Restaurant, verbose_name=_("Restaurant"), on_delete=models.CASCADE, related_name="dish_restaurant")
    category = models.ForeignKey(Category, verbose_name=_("Category"), on_delete=models.CASCADE, related_name="dish_category")
    slug = models.SlugField(_("Slug"), blank=True)


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Dish, self).save(*args, **kwargs)


class Review(models.Model):
    review = models.TextField(_("Review"), max_length=350)
    rate = models.PositiveSmallIntegerField(_("Rate"),
        validators=[MinValueValidator(1), MaxValueValidator(5)])
    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE, related_name="user_reviews")
    dish = models.ForeignKey(Dish, verbose_name=_("Dish"), on_delete=models.CASCADE, related_name="dish_reviews")
    created_at = models.DateTimeField(_("Created at"), default=timezone.now)

    def __str__(self):
        return f"{self.user} - {self.rate} - {self.review}"

restaurant/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Restaurant, Category, Dish


class ListRestaurants(ListView):
    model = Restaurant    


class DetailRestaurants(ListView):
    model = Dish
    template_name = 'restaurant/resturant_detail.html'
    
    def get_queryset(self):
        restaurant = Restaurant.objects.get(slug=self.kwargs['slug'])
        queryset = super().get_queryset().filter(restaurant=restaurant)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        restaurant = get_object_or_404(Restaurant, slug=self.kwargs['slug'])
        categories = restaurant.categories.all()
        context['restaurant'] = restaurant
        context['categories'] = categories
        return context


def dish_details(request, restaurant_slug, slug):
    dish = get_object_or_404(Dish, slug=slug)

    context = {
        'dish': dish,
    }

    return render(request, 'restaurant/dish_detail.html', context) 

restaurant/templates/restaurant/dish_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>{{ dish.restaurant }} - {{ dish.name }}</title>
{% endblock title %}

{% block cssfiles %}
    <link rel="stylesheet" href="{% static 'css/dish-details.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
{% endblock cssfiles %}

{% block body %}
    <div class="dish-details-container">
        <div class="dish-content">
            <!-- Dish Image on the Left -->
            <img src="{{ dish.image.url }}" alt="{{ dish.name }}" class="dish-image">

            <!-- Dish Info on the Right -->
            <div class="dish-info-container">
                <div class="dish-header">
                    <h1>{{ dish.name }}</h1>
                    <span class="dish-price">${{ dish.price }}</span>
                </div>
                <p class="dish-info-category-title">Category: <span class="dish-info-category-title-content ">{{ dish.category }}</span> </p>
                <p class="dish-description">{{ dish.description }}</p>

                <!--##To do Ingredients Section -->
                {% comment %} <div class="dish-ingredients">
                    <h3>Ingredients</h3>
                    <ul>
                        {% for ingredient in dish.ingredients %}
                            <li>{{ ingredient }}</li>
                        {% endfor %}
                    </ul>
                </div> {% endcomment %}

                <!-- Restaurant Info -->
                <p class="dish-restaurant-info">Available at: {{ dish.restaurant.name }}</p>

                <!-- Add to Cart Button -->
                <a href="#" class="add-to-cart-button">Add to Cart</a>
            </div>            
        </div>

        
    </div>
{% endblock body %}

{% block jscode %}
{% endblock jscode %}

restaurant/templates/restaurant/restaurant_list.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
    <title> Restaurant </title>
{% endblock title%}

{% block cssfiles%}
    <link rel="stylesheet" href="{% static 'css/dishes.css' %}">
{% endblock cssfiles%}

{% block body %}

<section>
    <h3>Dishes</h3>
    </section>
<section class="barb" id="biryani">
    <h1 class="barbeque">Restaurants</h1>
    <hr class="line"> 
    <div class="box-container">
        {% for restaurant in object_list %}
            <div class="box">
                <a href="{% url 'restaurant:detail_restaurant' restaurant.slug %}"><img src="{{restaurant.image.url}}"></a>
                <h3>{{restaurant}}</h3>
                <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                    <br>
                    <p>Starters,biryani,tandoori</p>
                </div>
            </div>
        {%endfor%}
    </div>
</section>




</section>


{% endblock body %}


{% block jscode %}


    <!--Java Script-->
    <script>
        let menu = document.querySelector('#menu-bars');
        let navbar = document.querySelector('.navbar');
        
        menu.onclick = () => {
            menu.classList.toggle('fa-times');
            navbar.classList.toggle('active');
        }
        window.onscroll=() => {
            menu.classList.remove('fa-times');
            navbar.classList.remove('active');
        }
        document.querySelector('#search-icon').onclick=() => {
            document.querySelector('#search-form').classList.toggle('active');
        }
        document.querySelector('#close1').onclick=() => {
            document.querySelector('#search-form').classList.toggle('active');
        }
        document.querySelector("#feedback").onclick=() =>{
        document.querySelector("#co1").classList.toggle("active");
    }
        document.querySelector("#close").onclick=() =>{
        document.querySelector("#co1").classList.toggle("active");
    }

        const btn = document.querySelector("button");
        const post = document.querySelector(".post");
        const widget = document.querySelector(".star-widget");
        const editBtn = document.querySelector(".edit");
    
        btn.onclick = () =>{
        widget.style.display = "none";
        post.style.display = "block";
        editBtn.onclick = () =>{
            widget.style.display = "block";
            post.style.display = "none";
        }
        return false;
    }

   
       
    </script>
    <!--JavaScript ends -->
{% endblock jscode %}

restaurant/templates/restaurant/resturant_detail.html
{% extends "base.html" %}
{% load static %}

{% block title%}
    <title> Restaurant - {{restaurant}} </title>
{% endblock title%}

{% block cssfiles%}
    <link rel="stylesheet" href="{% static 'css/fishland.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
{% endblock cssfiles%}


{% block body %}
<!--side bar-->
<nav class="sidebar">
    <div class="text">
    <a href="#"><i class="fa fa-home"></i></a>
    <ul>
        {% for category in categories %}    
            <li><a href="#{{category.slug}}" onclick="myfun()">{{category}}</a></li>
        {% endfor %}
    </ul>
</div>
</nav>
<!--Side bar ends-->
<section class="home" id="home">
    <div class="barb">
    <h2><img src="./Images/Restaurants/fishland.jpg" height="150"></h2>
    <div class="cont">
        <iframe width="420" height="315"
src="https://www.yout111ube.com/embed/zc8DJMgkQR4?autoplay=1&mute=1&loop=1&playlist=zc8DJMgkQR4&loop=1">
</iframe>
        </div>
        </div>
</section>

{% for category in categories %}
<section class="fastfood" id="{{category.slug}}">
    <h2 class="fastfood1">{{category}}</h2>
    <hr class="line">
    <h4>{{category}}</h4>
    <div class="box-fast-food">
    {% for dish in category.dish_category.all %}
        <div class="box">
            <img src="{{dish.image.url}}">
            <h3>{{dish.name}}</h3>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
    
            </div>
            <span>{{dish.price}}</span>
            <br>
            <a href="{% url 'restaurant:dish_details' dish.restaurant.slug dish.slug %}" class="btn">Show</a>
            <a href="#" class="btn">Add to cart</a>
            
        </div>
    {% endfor %}
    </div>
</section>
{%endfor%}

<div class="arrow">
    <a href="#home"><i class="fas fa-arrow-up"></i></a>
</div>

<!--Home  ends-->
{% endblock body %}

{% block jscode %}
<!--Java Script-->
<script>
    let menu = document.querySelector('#menu-bars');
    let navbar = document.querySelector('.navbar');
    
    menu.onclick = () => {
        menu.classList.toggle('fa-times');
        navbar.classList.toggle('active');
    }
    window.onscroll = () => {
        menu.classList.remove('fa-times');
        navbar.classList.remove('active');
    }
    
    function myfun() {
        document.querySelectorAll(".dish-category").forEach(section => {
            section.style.display = "block";
        });
    }
</script>
<!--JavaScript ends -->

{% endblock jscode %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title%}
    {% endblock title%}
    <link rel="icon" href="{% static 'images/download.png' %}" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    {% block cssfiles%}

    {% endblock cssfiles%}
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body onload="myload()">
    <div class="loader-container" id = "loader">
        <img src="{% static 'images/loader.gif' %}">
    </div>

    <!--Header section start-->
    <header>
        <a href="#" class="logo"><i class="fa fa-utensils"></i>Foodies.</a>
        <nav class="navbar">
            <a class="active" href="./home.html">Home</a>
            <a href="{% url 'restaurant:list_restaurant' %}">Restaurants</a>
            <a href="#" onclick="openAbout()">about</a>
            <a href="./contact.html" >Contact us</a>  
            <a href="#">Orders</a>
        </nav>
        <div class="icons">
            <i class="fas fa-bars" id="menu-bars"></i>
            <i class="fas fa-search" id="search-icon"></i>
            <a href="#" class="fas fa-heart"></a>
            <a href="#" class="fas fa-shopping-cart"></a>
            <i class="fa fa-user" aria-hidden="true"></i>
            <a href="login.html" class="fas fa-sign-in-alt"></a>
            
        </div>
    </header>
    <div class="back">
        <div class="container1" id="co1">
            <div class="post">
                <div class="text">Thanks for Rating us!</div>
                <div class="edit">Edit</div>
                <i class="fas fa-times" id="close"></i>
        
            </div>
            <div class="star-widget">
            <input type="radio" name="rate" id="rate-5">
            <label for="rate-5" class="fas fa-star"></label>
            <input type="radio" name="rate" id="rate-4">
            <label for="rate-4" class="fas fa-star"></label>
            <input type="radio" name="rate" id="rate-3">
            <label for="rate-3" class="fas fa-star"></label>
            <input type="radio" name="rate" id="rate-2">
            <label for="rate-2" class="fas fa-star"></label>
            <input type="radio" name="rate" id="rate-1">
            <label for="rate-1" class="fas fa-star"></label>
            <form action="#">
                <i class="fas fa-times" id="close"></i>
                <h4></h4>
                <div class="textarea">
                    <textarea cols="30" placeholder="Describe your experience"></textarea>
        
                </div>
                
                <div class="btn">
                    <button type="submit">Post</button>
                </div>
            </form>
            </div>    
        </div>
    </div>
    <!--Header section end-->
      <!--search form-->
      <form action="" id="search-form">
        <input type="search" placeholder="search here..." name="" id="search-box">
        <label for="search-box" class="fas fa-search"></label>
        <i class="fas fa-times" id="close1"></i>
    </form>
    <!--Search Form ends-->
    {% block body%}
    {% endblock body%}


<div id="about" class="about">
    <a href="#" class="closebtn" onclick="closeNav()">&times;</a>
    <div class="about-overlay">
        <h1>About us</h1>
        <p>Launched in 2021, Our technology platform connects customers,<br> 
        restaurant partners and delivery partners, serving their multiple needs. <br>
        Customers use our platform to search and discover restaurants, read and write customer 
        generated reviews and view and upload photos,<br> order food delivery, book a table and make 
        payments while dining-out at restaurants. On the other hand,<br> we provide restaurant partners 
        with industry-specific marketing tools which enable them to engage and acquire customers<br> to 
        grow their business while also providing a reliable <br>and efficient last mile delivery service. 
        We also operate a one-stop procurement solution, <br>Hyperpure, which supplies high quality ingredients 
        and kitchen products to restaurant partners.<br> We also provide our delivery partners with transparent 
        and flexible earning opportunities. </p>
    </div>
</div>
<!--Footer Section-->
<footer class="footer">
    <div class="container">
            <div class="row">
                <div class="footer-col">
                    <ul>
                        <i class="fa fa-utensils"></i>
                        <span>Foodies.</span>
                    </ul>
                    <div class="map">
                        <ul>
                            <i class="fa fa-map-marker"></i>
                                <span>5th Floor,
                                    A-118,Sangareddy, Hyderabad, Telangana - 502001
                                </span>
                        </ul>
                        </div>
                    <div class="mail">
                        <ul>
                            <i class="fas fa-inbox"></i>
                            <span>
                                support@foodies.com
                            </span>
                        </ul>
                    </div>
                </div>
                <div class="footer-col">
                    <h4>Foodies</h4>
                    <ul>
                        <li><a href="#" onclick="openAbout()">about us</a></li>
                        <li><a href="#">Our services</a></li>
                        <li><a href="#">Privacy policy</a></li>
                        <li><a href="#">Payment policy</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Get help</h4>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Delivery</a></li>
                        <li><a href="#">My orders</a></li>
                        <li><a href="#">Order Status</a></li>
                        <li><a href="#">Payment options</a></li>

                    </ul>
                    </div>
                    <div class="footer-col">
                        <h4>Order Now</h4>
                        <ul>
                            <li><a href="./dishes.html">Biryani's</a></li>
                            <li><a href="./dishes.html">Restaurants</a></li>
                            <li><a href="./dishes.html">Starters</a></li>
                            <li><a href="./dishes.html">Fast food</a></li>
                        </ul>
                    </div>
                    <div class="footer-col">
                        <h4>Follow us</h4>
                        <div class="social-links">
                            <a href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
                            <a href="https://twitter.com/login"><i class="fab fa-twitter"></i></a>
                            <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                            <a href="https://www.linkedin.com/login"><i class="fab fa-linkedin-in"></i></a>

                        </div>

                    </div>

                </div>
            </div>
    </div>
</footer>


<!--Java Script-->
    <script>
        let menu = document.querySelector('#menu-bars');
        let navbar = document.querySelector('.navbar');
        
        menu.onclick = () => {
            menu.classList.toggle('fa-times');
            navbar.classList.toggle('active');
        }
        window.onscroll=() => {
            menu.classList.remove('fa-times');
            navbar.classList.remove('active');
        }
        document.querySelector('#search-icon').onclick=() => {
            document.querySelector('#search-form').classList.toggle('active');
        }
        document.querySelector('#close1').onclick=() => {
            document.querySelector('#search-form').classList.toggle('active');
        }
        
        document.querySelector("#close").onclick=() =>{
        document.querySelector("#co1").classList.toggle("active");
    }
    var preloader = document.getElementById("loading");
    function myload() {
        preloader.style.display="none";
    }


        const btn = document.querySelector("button");
        const post = document.querySelector(".post");
        const widget = document.querySelector(".star-widget");
        const editBtn = document.querySelector(".edit");
    
        btn.onclick = () =>{
        widget.style.display = "none";
        post.style.display = "block";
        editBtn.onclick = () =>{
            widget.style.display = "block";
            post.style.display = "none";
        }
        return false;
    }
    function openAbout(){
        document.getElementById("about").style.width = "100%";

    }
    function closeNav(){
        document.getElementById("about").style.width = "0%";
    }
    var preloader = document.getElementById("loader");
    
    function myloader(){
        preloader.style.display = "none";
    }
    function mygrocery(){
        confirm("Order Now on Whatsapp click ok to continue");
    }
    </script>
    {% block jscode %}
    {% endblock jscode %}
    <!--JavaScript ends -->
</body>
</html>